/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddOn {
    #[serde(rename = "add_on")]
    pub add_on: Box<crate::models::AddOnObject>,
}

impl AddOn {
    pub fn new(add_on: crate::models::AddOnObject) -> AddOn {
        AddOn {
            add_on: Box::new(add_on),
        }
    }
}


