/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.21.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddOnInput {
    #[serde(rename = "add_on", skip_serializing_if = "Option::is_none")]
    pub add_on: Option<Box<crate::models::AddOnInputAddOn>>,
}

impl AddOnInput {
    pub fn new() -> AddOnInput {
        AddOnInput {
            add_on: None,
        }
    }
}


