/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppliedAddOnObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "lago_add_on_id")]
    pub lago_add_on_id: uuid::Uuid,
    #[serde(rename = "add_on_code")]
    pub add_on_code: String,
    #[serde(rename = "lago_customer_id")]
    pub lago_customer_id: uuid::Uuid,
    #[serde(rename = "external_customer_id")]
    pub external_customer_id: String,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    #[serde(rename = "amount_currency")]
    pub amount_currency: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl AppliedAddOnObject {
    pub fn new(lago_id: uuid::Uuid, lago_add_on_id: uuid::Uuid, add_on_code: String, lago_customer_id: uuid::Uuid, external_customer_id: String, amount_cents: i32, amount_currency: String, created_at: String) -> AppliedAddOnObject {
        AppliedAddOnObject {
            lago_id,
            lago_add_on_id,
            add_on_code,
            lago_customer_id,
            external_customer_id,
            amount_cents,
            amount_currency,
            created_at,
        }
    }
}


