/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppliedAddOn {
    #[serde(rename = "applied_add_on")]
    pub applied_add_on: Box<crate::models::AppliedAddOnObject>,
}

impl AppliedAddOn {
    pub fn new(applied_add_on: crate::models::AppliedAddOnObject) -> AppliedAddOn {
        AppliedAddOn {
            applied_add_on: Box::new(applied_add_on),
        }
    }
}


