/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.20.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppliedAddOnObject {
    #[serde(rename = "lago_id", skip_serializing_if = "Option::is_none")]
    pub lago_id: Option<String>,
    #[serde(rename = "lago_add_on_id", skip_serializing_if = "Option::is_none")]
    pub lago_add_on_id: Option<String>,
    #[serde(rename = "add_on_code", skip_serializing_if = "Option::is_none")]
    pub add_on_code: Option<String>,
    #[serde(rename = "lago_customer_id", skip_serializing_if = "Option::is_none")]
    pub lago_customer_id: Option<String>,
    #[serde(rename = "external_customer_id", skip_serializing_if = "Option::is_none")]
    pub external_customer_id: Option<String>,
    #[serde(rename = "amount_cents", skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
    #[serde(rename = "amount_currency", skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl AppliedAddOnObject {
    pub fn new() -> AppliedAddOnObject {
        AppliedAddOnObject {
            lago_id: None,
            lago_add_on_id: None,
            add_on_code: None,
            lago_customer_id: None,
            external_customer_id: None,
            amount_cents: None,
            amount_currency: None,
            created_at: None,
        }
    }
}


