/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppliedCouponsPaginated {
    #[serde(rename = "applied_coupons")]
    pub applied_coupons: Vec<crate::models::AppliedCouponObjectExtended>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl AppliedCouponsPaginated {
    pub fn new(applied_coupons: Vec<crate::models::AppliedCouponObjectExtended>, meta: crate::models::PaginationMeta) -> AppliedCouponsPaginated {
        AppliedCouponsPaginated {
            applied_coupons,
            meta: Box::new(meta),
        }
    }
}


