/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.20.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppliedAddOn {
    #[serde(rename = "applied_add_on", skip_serializing_if = "Option::is_none")]
    pub applied_add_on: Option<Box<crate::models::AppliedAddOnObject>>,
}

impl AppliedAddOn {
    pub fn new() -> AppliedAddOn {
        AppliedAddOn {
            applied_add_on: None,
        }
    }
}


