/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppliedCoupon {
    #[serde(rename = "applied_coupon")]
    pub applied_coupon: Box<crate::models::AppliedCouponObject>,
}

impl AppliedCoupon {
    pub fn new(applied_coupon: crate::models::AppliedCouponObject) -> AppliedCoupon {
        AppliedCoupon {
            applied_coupon: Box::new(applied_coupon),
        }
    }
}


