/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AppliedCouponObjectExtended {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "lago_coupon_id")]
    pub lago_coupon_id: uuid::Uuid,
    #[serde(rename = "coupon_code")]
    pub coupon_code: String,
    #[serde(rename = "lago_customer_id")]
    pub lago_customer_id: uuid::Uuid,
    #[serde(rename = "external_customer_id")]
    pub external_customer_id: String,
    /// Status
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    #[serde(rename = "amount_cents_remaining", skip_serializing_if = "Option::is_none")]
    pub amount_cents_remaining: Option<i32>,
    #[serde(rename = "amount_currency")]
    pub amount_currency: String,
    #[serde(rename = "percentage_rate", skip_serializing_if = "Option::is_none")]
    pub percentage_rate: Option<f32>,
    /// Frequency type
    #[serde(rename = "frequency")]
    pub frequency: Frequency,
    #[serde(rename = "frequency_duration", skip_serializing_if = "Option::is_none")]
    pub frequency_duration: Option<i32>,
    #[serde(rename = "frequency_duration_remaining", skip_serializing_if = "Option::is_none")]
    pub frequency_duration_remaining: Option<i32>,
    #[serde(rename = "expiration_at", skip_serializing_if = "Option::is_none")]
    pub expiration_at: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "terminated_at", skip_serializing_if = "Option::is_none")]
    pub terminated_at: Option<String>,
    #[serde(rename = "credits")]
    pub credits: Vec<crate::models::CreditObject>,
}

impl AppliedCouponObjectExtended {
    pub fn new(lago_id: uuid::Uuid, lago_coupon_id: uuid::Uuid, coupon_code: String, lago_customer_id: uuid::Uuid, external_customer_id: String, status: Status, amount_cents: i32, amount_currency: String, frequency: Frequency, created_at: String, credits: Vec<crate::models::CreditObject>) -> AppliedCouponObjectExtended {
        AppliedCouponObjectExtended {
            lago_id,
            lago_coupon_id,
            coupon_code,
            lago_customer_id,
            external_customer_id,
            status,
            amount_cents,
            amount_cents_remaining: None,
            amount_currency,
            percentage_rate: None,
            frequency,
            frequency_duration: None,
            frequency_duration_remaining: None,
            expiration_at: None,
            created_at,
            terminated_at: None,
            credits,
        }
    }
}

/// Status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "terminated")]
    Terminated,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// Frequency type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Frequency {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "recurring")]
    Recurring,
}

impl Default for Frequency {
    fn default() -> Frequency {
        Self::Once
    }
}

