/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BatchEventInputEvent {
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    #[serde(rename = "external_customer_id", skip_serializing_if = "Option::is_none")]
    pub external_customer_id: Option<String>,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i32>,
    #[serde(rename = "external_subscription_ids")]
    pub external_subscription_ids: Vec<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl BatchEventInputEvent {
    pub fn new(transaction_id: String, code: String, external_subscription_ids: Vec<String>) -> BatchEventInputEvent {
        BatchEventInputEvent {
            transaction_id,
            external_customer_id: None,
            code,
            timestamp: None,
            external_subscription_ids,
            properties: None,
        }
    }
}


