/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.20.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BillableMetrics {
    #[serde(rename = "billable_metrics", skip_serializing_if = "Option::is_none")]
    pub billable_metrics: Option<Vec<crate::models::BillableMetricObject>>,
}

impl BillableMetrics {
    pub fn new() -> BillableMetrics {
        BillableMetrics {
            billable_metrics: None,
        }
    }
}


