/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BillableMetricObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "field_name", skip_serializing_if = "Option::is_none")]
    pub field_name: Option<String>,
    /// Aggregation type
    #[serde(rename = "aggregation_type")]
    pub aggregation_type: AggregationType,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<crate::models::BillableMetricGroup>>,
    #[serde(rename = "active_subscriptions_count")]
    pub active_subscriptions_count: i32,
    #[serde(rename = "draft_invoices_count")]
    pub draft_invoices_count: i32,
    #[serde(rename = "plans_count")]
    pub plans_count: i32,
}

impl BillableMetricObject {
    pub fn new(lago_id: uuid::Uuid, name: String, code: String, created_at: String, aggregation_type: AggregationType, active_subscriptions_count: i32, draft_invoices_count: i32, plans_count: i32) -> BillableMetricObject {
        BillableMetricObject {
            lago_id,
            name,
            code,
            description: None,
            created_at,
            field_name: None,
            aggregation_type,
            group: None,
            active_subscriptions_count,
            draft_invoices_count,
            plans_count,
        }
    }
}

/// Aggregation type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AggregationType {
    #[serde(rename = "count_agg")]
    CountAgg,
    #[serde(rename = "sum_agg")]
    SumAgg,
    #[serde(rename = "max_agg")]
    MaxAgg,
    #[serde(rename = "unique_count_agg")]
    UniqueCountAgg,
    #[serde(rename = "recurring_count_agg")]
    RecurringCountAgg,
}

impl Default for AggregationType {
    fn default() -> AggregationType {
        Self::CountAgg
    }
}

