/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BillableMetric {
    #[serde(rename = "billable_metric")]
    pub billable_metric: Box<crate::models::BillableMetricObject>,
}

impl BillableMetric {
    pub fn new(billable_metric: crate::models::BillableMetricObject) -> BillableMetric {
        BillableMetric {
            billable_metric: Box::new(billable_metric),
        }
    }
}


