/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BillableMetricGroup {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "values")]
    pub values: Vec<crate::models::BillableMetricGroupValuesInner>,
}

impl BillableMetricGroup {
    pub fn new(key: String, values: Vec<crate::models::BillableMetricGroupValuesInner>) -> BillableMetricGroup {
        BillableMetricGroup {
            key,
            values,
        }
    }
}


