/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.21.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BillingConfigurationOrganization {
    #[serde(rename = "invoice_footer", skip_serializing_if = "Option::is_none")]
    pub invoice_footer: Option<String>,
    #[serde(rename = "invoice_grace_period", skip_serializing_if = "Option::is_none")]
    pub invoice_grace_period: Option<i32>,
    #[serde(rename = "vat_rate", skip_serializing_if = "Option::is_none")]
    pub vat_rate: Option<f32>,
}

impl BillingConfigurationOrganization {
    pub fn new() -> BillingConfigurationOrganization {
        BillingConfigurationOrganization {
            invoice_footer: None,
            invoice_grace_period: None,
            vat_rate: None,
        }
    }
}


