/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.20.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChargeObject {
    #[serde(rename = "lago_id", skip_serializing_if = "Option::is_none")]
    pub lago_id: Option<String>,
    #[serde(rename = "lago_billable_metric_id", skip_serializing_if = "Option::is_none")]
    pub lago_billable_metric_id: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Charge model type
    #[serde(rename = "charge_model", skip_serializing_if = "Option::is_none")]
    pub charge_model: Option<ChargeModel>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
    #[serde(rename = "group_properties", skip_serializing_if = "Option::is_none")]
    pub group_properties: Option<Vec<crate::models::GroupPropertiesObject>>,
}

impl ChargeObject {
    pub fn new() -> ChargeObject {
        ChargeObject {
            lago_id: None,
            lago_billable_metric_id: None,
            created_at: None,
            charge_model: None,
            properties: None,
            group_properties: None,
        }
    }
}

/// Charge model type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChargeModel {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "graduated")]
    Graduated,
    #[serde(rename = "package")]
    Package,
    #[serde(rename = "percentage")]
    Percentage,
    #[serde(rename = "volume")]
    Volume,
}

impl Default for ChargeModel {
    fn default() -> ChargeModel {
        Self::Standard
    }
}

