/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.20.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChargeUsageObject {
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<f32>,
    #[serde(rename = "amount_cents", skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
    #[serde(rename = "amount_currency", skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<String>,
    #[serde(rename = "charge", skip_serializing_if = "Option::is_none")]
    pub charge: Option<Box<crate::models::ChargeUsageObjectCharge>>,
    #[serde(rename = "billable_metric", skip_serializing_if = "Option::is_none")]
    pub billable_metric: Option<Box<crate::models::ChargeUsageObjectBillableMetric>>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<crate::models::ChargeUsageObjectGroupsInner>>,
}

impl ChargeUsageObject {
    pub fn new() -> ChargeUsageObject {
        ChargeUsageObject {
            units: None,
            amount_cents: None,
            amount_currency: None,
            charge: None,
            billable_metric: None,
            groups: None,
        }
    }
}


