/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChargeUsageObject {
    #[serde(rename = "units")]
    pub units: f32,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    #[serde(rename = "amount_currency")]
    pub amount_currency: String,
    #[serde(rename = "charge")]
    pub charge: Box<crate::models::ChargeUsageObjectCharge>,
    #[serde(rename = "billable_metric")]
    pub billable_metric: Box<crate::models::ChargeUsageObjectBillableMetric>,
    #[serde(rename = "groups")]
    pub groups: Vec<crate::models::ChargeUsageObjectGroupsInner>,
}

impl ChargeUsageObject {
    pub fn new(units: f32, amount_cents: i32, amount_currency: String, charge: crate::models::ChargeUsageObjectCharge, billable_metric: crate::models::ChargeUsageObjectBillableMetric, groups: Vec<crate::models::ChargeUsageObjectGroupsInner>) -> ChargeUsageObject {
        ChargeUsageObject {
            units,
            amount_cents,
            amount_currency,
            charge: Box::new(charge),
            billable_metric: Box::new(billable_metric),
            groups,
        }
    }
}


