/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChargeObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "lago_billable_metric_id")]
    pub lago_billable_metric_id: uuid::Uuid,
    #[serde(rename = "billable_metric_code")]
    pub billable_metric_code: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Charge model type
    #[serde(rename = "charge_model")]
    pub charge_model: ChargeModel,
    #[serde(rename = "instant", skip_serializing_if = "Option::is_none")]
    pub instant: Option<bool>,
    #[serde(rename = "min_amount_cents", skip_serializing_if = "Option::is_none")]
    pub min_amount_cents: Option<i32>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
    #[serde(rename = "group_properties", skip_serializing_if = "Option::is_none")]
    pub group_properties: Option<Vec<crate::models::GroupPropertiesObject>>,
}

impl ChargeObject {
    pub fn new(lago_id: uuid::Uuid, lago_billable_metric_id: uuid::Uuid, billable_metric_code: String, created_at: String, charge_model: ChargeModel) -> ChargeObject {
        ChargeObject {
            lago_id,
            lago_billable_metric_id,
            billable_metric_code,
            created_at,
            charge_model,
            instant: None,
            min_amount_cents: None,
            properties: None,
            group_properties: None,
        }
    }
}

/// Charge model type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChargeModel {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "graduated")]
    Graduated,
    #[serde(rename = "package")]
    Package,
    #[serde(rename = "percentage")]
    Percentage,
    #[serde(rename = "volume")]
    Volume,
}

impl Default for ChargeModel {
    fn default() -> ChargeModel {
        Self::Standard
    }
}

