/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CouponInputCouponAppliesTo {
    #[serde(rename = "plan_codes", skip_serializing_if = "Option::is_none")]
    pub plan_codes: Option<Vec<String>>,
    #[serde(rename = "billable_metric_codes", skip_serializing_if = "Option::is_none")]
    pub billable_metric_codes: Option<Vec<String>>,
}

impl CouponInputCouponAppliesTo {
    pub fn new() -> CouponInputCouponAppliesTo {
        CouponInputCouponAppliesTo {
            plan_codes: None,
            billable_metric_codes: None,
        }
    }
}


