/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CouponInput {
    #[serde(rename = "coupon")]
    pub coupon: Box<crate::models::CouponInputCoupon>,
}

impl CouponInput {
    pub fn new(coupon: crate::models::CouponInputCoupon) -> CouponInput {
        CouponInput {
            coupon: Box::new(coupon),
        }
    }
}


