/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CouponObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "code")]
    pub code: String,
    /// Coupon type
    #[serde(rename = "coupon_type")]
    pub coupon_type: CouponType,
    #[serde(rename = "amount_cents", skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
    #[serde(rename = "amount_currency", skip_serializing_if = "Option::is_none")]
    pub amount_currency: Option<String>,
    #[serde(rename = "reusable", skip_serializing_if = "Option::is_none")]
    pub reusable: Option<bool>,
    #[serde(rename = "limited_plans", skip_serializing_if = "Option::is_none")]
    pub limited_plans: Option<bool>,
    #[serde(rename = "plan_codes", skip_serializing_if = "Option::is_none")]
    pub plan_codes: Option<Vec<String>>,
    #[serde(rename = "limited_billable_metrics", skip_serializing_if = "Option::is_none")]
    pub limited_billable_metrics: Option<bool>,
    #[serde(rename = "billable_metric_codes", skip_serializing_if = "Option::is_none")]
    pub billable_metric_codes: Option<Vec<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "percentage_rate", skip_serializing_if = "Option::is_none")]
    pub percentage_rate: Option<f32>,
    /// Frequency type
    #[serde(rename = "frequency")]
    pub frequency: Frequency,
    #[serde(rename = "frequency_duration", skip_serializing_if = "Option::is_none")]
    pub frequency_duration: Option<i32>,
    #[serde(rename = "expiration_at", skip_serializing_if = "Option::is_none")]
    pub expiration_at: Option<String>,
    /// Expiration type
    #[serde(rename = "expiration")]
    pub expiration: Expiration,
}

impl CouponObject {
    pub fn new(lago_id: uuid::Uuid, name: String, code: String, coupon_type: CouponType, created_at: String, frequency: Frequency, expiration: Expiration) -> CouponObject {
        CouponObject {
            lago_id,
            name,
            code,
            coupon_type,
            amount_cents: None,
            amount_currency: None,
            reusable: None,
            limited_plans: None,
            plan_codes: None,
            limited_billable_metrics: None,
            billable_metric_codes: None,
            created_at,
            percentage_rate: None,
            frequency,
            frequency_duration: None,
            expiration_at: None,
            expiration,
        }
    }
}

/// Coupon type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CouponType {
    #[serde(rename = "fixed_amount")]
    FixedAmount,
    #[serde(rename = "percentage")]
    Percentage,
}

impl Default for CouponType {
    fn default() -> CouponType {
        Self::FixedAmount
    }
}
/// Frequency type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Frequency {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "recurring")]
    Recurring,
}

impl Default for Frequency {
    fn default() -> Frequency {
        Self::Once
    }
}
/// Expiration type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Expiration {
    #[serde(rename = "no_expiration")]
    NoExpiration,
    #[serde(rename = "time_limit")]
    TimeLimit,
}

impl Default for Expiration {
    fn default() -> Expiration {
        Self::NoExpiration
    }
}

