/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditNotes {
    #[serde(rename = "credit_notes")]
    pub credit_notes: Vec<crate::models::CreditNoteObject>,
}

impl CreditNotes {
    pub fn new(credit_notes: Vec<crate::models::CreditNoteObject>) -> CreditNotes {
        CreditNotes {
            credit_notes,
        }
    }
}


