/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditNoteInputCreditNoteItemsInner {
    #[serde(rename = "fee_id")]
    pub fee_id: uuid::Uuid,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
}

impl CreditNoteInputCreditNoteItemsInner {
    pub fn new(fee_id: uuid::Uuid, amount_cents: i32) -> CreditNoteInputCreditNoteItemsInner {
        CreditNoteInputCreditNoteItemsInner {
            fee_id,
            amount_cents,
        }
    }
}


