/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditNoteObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "sequential_id")]
    pub sequential_id: i32,
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "lago_invoice_id")]
    pub lago_invoice_id: uuid::Uuid,
    #[serde(rename = "invoice_number")]
    pub invoice_number: String,
    #[serde(rename = "issuing_date")]
    pub issuing_date: String,
    /// Credit status
    #[serde(rename = "credit_status", skip_serializing_if = "Option::is_none")]
    pub credit_status: Option<CreditStatus>,
    /// Refund status
    #[serde(rename = "refund_status", skip_serializing_if = "Option::is_none")]
    pub refund_status: Option<RefundStatus>,
    /// Reason
    #[serde(rename = "reason")]
    pub reason: Reason,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "total_amount_cents")]
    pub total_amount_cents: i32,
    #[serde(rename = "total_amount_currency")]
    pub total_amount_currency: String,
    #[serde(rename = "vat_amount_cents")]
    pub vat_amount_cents: i32,
    #[serde(rename = "vat_amount_currency")]
    pub vat_amount_currency: String,
    #[serde(rename = "sub_total_vat_excluded_amount_cents")]
    pub sub_total_vat_excluded_amount_cents: i32,
    #[serde(rename = "sub_total_vat_excluded_amount_currency")]
    pub sub_total_vat_excluded_amount_currency: String,
    #[serde(rename = "balance_amount_cents")]
    pub balance_amount_cents: i32,
    #[serde(rename = "balance_amount_currency")]
    pub balance_amount_currency: String,
    #[serde(rename = "credit_amount_cents")]
    pub credit_amount_cents: i32,
    #[serde(rename = "credit_amount_currency")]
    pub credit_amount_currency: String,
    #[serde(rename = "refund_amount_cents")]
    pub refund_amount_cents: i32,
    #[serde(rename = "refund_amount_currency")]
    pub refund_amount_currency: String,
    #[serde(rename = "coupons_adjustement_amount_cents")]
    pub coupons_adjustement_amount_cents: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "file_url", skip_serializing_if = "Option::is_none")]
    pub file_url: Option<String>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::CreditNoteItemObject>>,
}

impl CreditNoteObject {
    pub fn new(lago_id: uuid::Uuid, sequential_id: i32, number: String, lago_invoice_id: uuid::Uuid, invoice_number: String, issuing_date: String, reason: Reason, currency: String, total_amount_cents: i32, total_amount_currency: String, vat_amount_cents: i32, vat_amount_currency: String, sub_total_vat_excluded_amount_cents: i32, sub_total_vat_excluded_amount_currency: String, balance_amount_cents: i32, balance_amount_currency: String, credit_amount_cents: i32, credit_amount_currency: String, refund_amount_cents: i32, refund_amount_currency: String, coupons_adjustement_amount_cents: i32, created_at: String, updated_at: String) -> CreditNoteObject {
        CreditNoteObject {
            lago_id,
            sequential_id,
            number,
            lago_invoice_id,
            invoice_number,
            issuing_date,
            credit_status: None,
            refund_status: None,
            reason,
            description: None,
            currency,
            total_amount_cents,
            total_amount_currency,
            vat_amount_cents,
            vat_amount_currency,
            sub_total_vat_excluded_amount_cents,
            sub_total_vat_excluded_amount_currency,
            balance_amount_cents,
            balance_amount_currency,
            credit_amount_cents,
            credit_amount_currency,
            refund_amount_cents,
            refund_amount_currency,
            coupons_adjustement_amount_cents,
            created_at,
            updated_at,
            file_url: None,
            items: None,
        }
    }
}

/// Credit status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreditStatus {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "consumed")]
    Consumed,
    #[serde(rename = "voided")]
    Voided,
}

impl Default for CreditStatus {
    fn default() -> CreditStatus {
        Self::Available
    }
}
/// Refund status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefundStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for RefundStatus {
    fn default() -> RefundStatus {
        Self::Pending
    }
}
/// Reason
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "duplicated_charge")]
    DuplicatedCharge,
    #[serde(rename = "product_unsatisfactory")]
    ProductUnsatisfactory,
    #[serde(rename = "order_change")]
    OrderChange,
    #[serde(rename = "order_cancellation")]
    OrderCancellation,
    #[serde(rename = "fraudulent_charge")]
    FraudulentCharge,
    #[serde(rename = "other")]
    Other,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::DuplicatedCharge
    }
}

