/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditObjectItem {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl CreditObjectItem {
    pub fn new(lago_id: uuid::Uuid, r#type: String, code: String, name: String) -> CreditObjectItem {
        CreditObjectItem {
            lago_id,
            r#type,
            code,
            name,
        }
    }
}


