/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    #[serde(rename = "amount_currency")]
    pub amount_currency: String,
    #[serde(rename = "before_vat")]
    pub before_vat: bool,
    #[serde(rename = "item")]
    pub item: Box<crate::models::CreditObjectItem>,
    #[serde(rename = "invoice")]
    pub invoice: Box<crate::models::CreditObjectInvoice>,
}

impl CreditObject {
    pub fn new(lago_id: uuid::Uuid, amount_cents: i32, amount_currency: String, before_vat: bool, item: crate::models::CreditObjectItem, invoice: crate::models::CreditObjectInvoice) -> CreditObject {
        CreditObject {
            lago_id,
            amount_cents,
            amount_currency,
            before_vat,
            item: Box::new(item),
            invoice: Box::new(invoice),
        }
    }
}


