/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditNoteItemObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    #[serde(rename = "amount_currency")]
    pub amount_currency: String,
    #[serde(rename = "fee")]
    pub fee: Box<crate::models::FeeObject>,
}

impl CreditNoteItemObject {
    pub fn new(lago_id: uuid::Uuid, amount_cents: i32, amount_currency: String, fee: crate::models::FeeObject) -> CreditNoteItemObject {
        CreditNoteItemObject {
            lago_id,
            amount_cents,
            amount_currency,
            fee: Box::new(fee),
        }
    }
}


