/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditNoteInputCreditNote {
    #[serde(rename = "invoice_id")]
    pub invoice_id: uuid::Uuid,
    /// Reason
    #[serde(rename = "reason")]
    pub reason: Reason,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "credit_amount_cents")]
    pub credit_amount_cents: i32,
    #[serde(rename = "refund_amount_cents")]
    pub refund_amount_cents: i32,
    #[serde(rename = "items")]
    pub items: Vec<crate::models::CreditNoteInputCreditNoteItemsInner>,
}

impl CreditNoteInputCreditNote {
    pub fn new(invoice_id: uuid::Uuid, reason: Reason, credit_amount_cents: i32, refund_amount_cents: i32, items: Vec<crate::models::CreditNoteInputCreditNoteItemsInner>) -> CreditNoteInputCreditNote {
        CreditNoteInputCreditNote {
            invoice_id,
            reason,
            description: None,
            credit_amount_cents,
            refund_amount_cents,
            items,
        }
    }
}

/// Reason
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "duplicated_charge")]
    DuplicatedCharge,
    #[serde(rename = "product_unsatisfactory")]
    ProductUnsatisfactory,
    #[serde(rename = "order_change")]
    OrderChange,
    #[serde(rename = "order_cancellation")]
    OrderCancellation,
    #[serde(rename = "fraudulent_charge")]
    FraudulentCharge,
    #[serde(rename = "other")]
    Other,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::DuplicatedCharge
    }
}

