/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomersPaginated {
    #[serde(rename = "customers")]
    pub customers: Vec<crate::models::CustomerObject>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl CustomersPaginated {
    pub fn new(customers: Vec<crate::models::CustomerObject>, meta: crate::models::PaginationMeta) -> CustomersPaginated {
        CustomersPaginated {
            customers,
            meta: Box::new(meta),
        }
    }
}


