/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.20.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomerUsage {
    #[serde(rename = "customer_usage", skip_serializing_if = "Option::is_none")]
    pub customer_usage: Option<Box<crate::models::CustomerUsageObject>>,
}

impl CustomerUsage {
    pub fn new() -> CustomerUsage {
        CustomerUsage {
            customer_usage: None,
        }
    }
}


