/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomerUsageObject {
    #[serde(rename = "from_datetime")]
    pub from_datetime: String,
    #[serde(rename = "to_datetime")]
    pub to_datetime: String,
    #[serde(rename = "issuing_date")]
    pub issuing_date: String,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    #[serde(rename = "amount_currency")]
    pub amount_currency: String,
    #[serde(rename = "total_amount_cents")]
    pub total_amount_cents: i32,
    #[serde(rename = "total_amount_currency")]
    pub total_amount_currency: String,
    #[serde(rename = "vat_amount_cents")]
    pub vat_amount_cents: i32,
    #[serde(rename = "vat_amount_currency")]
    pub vat_amount_currency: String,
    #[serde(rename = "charges_usage")]
    pub charges_usage: Vec<crate::models::ChargeUsageObject>,
}

impl CustomerUsageObject {
    pub fn new(from_datetime: String, to_datetime: String, issuing_date: String, amount_cents: i32, amount_currency: String, total_amount_cents: i32, total_amount_currency: String, vat_amount_cents: i32, vat_amount_currency: String, charges_usage: Vec<crate::models::ChargeUsageObject>) -> CustomerUsageObject {
        CustomerUsageObject {
            from_datetime,
            to_datetime,
            issuing_date,
            amount_cents,
            amount_currency,
            total_amount_cents,
            total_amount_currency,
            vat_amount_cents,
            vat_amount_currency,
            charges_usage,
        }
    }
}


