/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventInput {
    #[serde(rename = "event")]
    pub event: Box<crate::models::EventInputEvent>,
}

impl EventInput {
    pub fn new(event: crate::models::EventInputEvent) -> EventInput {
        EventInput {
            event: Box::new(event),
        }
    }
}


