/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.21.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeeObjectItem {
    /// Billing time
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl FeeObjectItem {
    pub fn new() -> FeeObjectItem {
        FeeObjectItem {
            r#type: None,
            code: None,
            name: None,
        }
    }
}

/// Billing time
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "charge")]
    Charge,
    #[serde(rename = "add_on")]
    AddOn,
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "credit")]
    Credit,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Charge
    }
}

