/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeeObjectItem {
    /// Billing time
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "lago_item_id")]
    pub lago_item_id: uuid::Uuid,
    #[serde(rename = "item_type")]
    pub item_type: ItemType,
}

impl FeeObjectItem {
    pub fn new(r#type: RHashType, code: String, name: String, lago_item_id: uuid::Uuid, item_type: ItemType) -> FeeObjectItem {
        FeeObjectItem {
            r#type,
            code,
            name,
            lago_item_id,
            item_type,
        }
    }
}

/// Billing time
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "charge")]
    Charge,
    #[serde(rename = "add_on")]
    AddOn,
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "credit")]
    Credit,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Charge
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ItemType {
    #[serde(rename = "AddOn")]
    AddOn,
    #[serde(rename = "BillableMetric")]
    BillableMetric,
    #[serde(rename = "Subscription")]
    Subscription,
    #[serde(rename = "WalletTransaction")]
    WalletTransaction,
}

impl Default for ItemType {
    fn default() -> ItemType {
        Self::AddOn
    }
}

