/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeesPaginated {
    #[serde(rename = "fees")]
    pub fees: Vec<crate::models::FeeObject>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl FeesPaginated {
    pub fn new(fees: Vec<crate::models::FeeObject>, meta: crate::models::PaginationMeta) -> FeesPaginated {
        FeesPaginated {
            fees,
            meta: Box::new(meta),
        }
    }
}


