/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeesPaginatedAllOf {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl FeesPaginatedAllOf {
    pub fn new(meta: crate::models::PaginationMeta) -> FeesPaginatedAllOf {
        FeesPaginatedAllOf {
            meta: Box::new(meta),
        }
    }
}


