/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCustomerPortalUrl200ResponseCustomer {
    #[serde(rename = "portal_url")]
    pub portal_url: String,
}

impl GetCustomerPortalUrl200ResponseCustomer {
    pub fn new(portal_url: String) -> GetCustomerPortalUrl200ResponseCustomer {
        GetCustomerPortalUrl200ResponseCustomer {
            portal_url,
        }
    }
}


