/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoicesPaginated {
    #[serde(rename = "invoices")]
    pub invoices: Vec<crate::models::InvoiceObject>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl InvoicesPaginated {
    pub fn new(invoices: Vec<crate::models::InvoiceObject>, meta: crate::models::PaginationMeta) -> InvoicesPaginated {
        InvoicesPaginated {
            invoices,
            meta: Box::new(meta),
        }
    }
}


