/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceOneOffInputInvoice {
    #[serde(rename = "external_customer_id")]
    pub external_customer_id: String,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "fees", skip_serializing_if = "Option::is_none")]
    pub fees: Option<Vec<crate::models::InvoiceOneOffInputInvoiceFeesInner>>,
}

impl InvoiceOneOffInputInvoice {
    pub fn new(external_customer_id: String) -> InvoiceOneOffInputInvoice {
        InvoiceOneOffInputInvoice {
            external_customer_id,
            currency: None,
            fees: None,
        }
    }
}


