/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.21.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Invoice {
    #[serde(rename = "invoice", skip_serializing_if = "Option::is_none")]
    pub invoice: Option<Box<crate::models::InvoiceObject>>,
}

impl Invoice {
    pub fn new() -> Invoice {
        Invoice {
            invoice: None,
        }
    }
}


