/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvoiceOneOffInputInvoiceFeesInner {
    #[serde(rename = "add_on_code")]
    pub add_on_code: String,
    #[serde(rename = "unit_amount_cents", skip_serializing_if = "Option::is_none")]
    pub unit_amount_cents: Option<i32>,
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<f32>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl InvoiceOneOffInputInvoiceFeesInner {
    pub fn new(add_on_code: String) -> InvoiceOneOffInputInvoiceFeesInner {
        InvoiceOneOffInputInvoiceFeesInner {
            add_on_code,
            unit_amount_cents: None,
            units: None,
            description: None,
        }
    }
}


