/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaginationMeta {
    /// Current page
    #[serde(rename = "current_page")]
    pub current_page: i32,
    /// Next page
    #[serde(rename = "next_page", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<i32>,
    /// Previous page
    #[serde(rename = "prev_page", skip_serializing_if = "Option::is_none")]
    pub prev_page: Option<i32>,
    /// Total number of pages
    #[serde(rename = "total_pages")]
    pub total_pages: i32,
    /// Total number of records
    #[serde(rename = "total_count")]
    pub total_count: i32,
}

impl PaginationMeta {
    pub fn new(current_page: i32, total_pages: i32, total_count: i32) -> PaginationMeta {
        PaginationMeta {
            current_page,
            next_page: None,
            prev_page: None,
            total_pages,
            total_count,
        }
    }
}


