/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlanObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "code")]
    pub code: String,
    /// Plan interval
    #[serde(rename = "interval")]
    pub interval: Interval,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i32,
    #[serde(rename = "amount_currency")]
    pub amount_currency: String,
    #[serde(rename = "trial_period", skip_serializing_if = "Option::is_none")]
    pub trial_period: Option<f32>,
    #[serde(rename = "pay_in_advance", skip_serializing_if = "Option::is_none")]
    pub pay_in_advance: Option<bool>,
    #[serde(rename = "bill_charges_monthly", skip_serializing_if = "Option::is_none")]
    pub bill_charges_monthly: Option<bool>,
    #[serde(rename = "active_subscriptions_count")]
    pub active_subscriptions_count: i32,
    #[serde(rename = "draft_invoices_count")]
    pub draft_invoices_count: i32,
    #[serde(rename = "charges", skip_serializing_if = "Option::is_none")]
    pub charges: Option<Vec<crate::models::ChargeObject>>,
}

impl PlanObject {
    pub fn new(lago_id: uuid::Uuid, name: String, created_at: String, code: String, interval: Interval, amount_cents: i32, amount_currency: String, active_subscriptions_count: i32, draft_invoices_count: i32) -> PlanObject {
        PlanObject {
            lago_id,
            name,
            created_at,
            code,
            interval,
            description: None,
            amount_cents,
            amount_currency,
            trial_period: None,
            pay_in_advance: None,
            bill_charges_monthly: None,
            active_subscriptions_count,
            draft_invoices_count,
            charges: None,
        }
    }
}

/// Plan interval
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Interval {
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "monthly")]
    Monthly,
    #[serde(rename = "yearly")]
    Yearly,
}

impl Default for Interval {
    fn default() -> Interval {
        Self::Weekly
    }
}

