/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlansPaginated {
    #[serde(rename = "plans")]
    pub plans: Vec<crate::models::PlanObject>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl PlansPaginated {
    pub fn new(plans: Vec<crate::models::PlanObject>, meta: crate::models::PaginationMeta) -> PlansPaginated {
        PlansPaginated {
            plans,
            meta: Box::new(meta),
        }
    }
}


