/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlanInputPlanChargesInnerGroupPropertiesInner {
    #[serde(rename = "group_id")]
    pub group_id: String,
    #[serde(rename = "values")]
    pub values: serde_json::Value,
}

impl PlanInputPlanChargesInnerGroupPropertiesInner {
    pub fn new(group_id: String, values: serde_json::Value) -> PlanInputPlanChargesInnerGroupPropertiesInner {
        PlanInputPlanChargesInnerGroupPropertiesInner {
            group_id,
            values,
        }
    }
}


