/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscriptionsPaginated {
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<crate::models::SubscriptionObject>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl SubscriptionsPaginated {
    pub fn new(subscriptions: Vec<crate::models::SubscriptionObject>, meta: crate::models::PaginationMeta) -> SubscriptionsPaginated {
        SubscriptionsPaginated {
            subscriptions,
            meta: Box::new(meta),
        }
    }
}


