/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscriptionObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "external_id")]
    pub external_id: String,
    #[serde(rename = "lago_customer_id")]
    pub lago_customer_id: uuid::Uuid,
    #[serde(rename = "external_customer_id")]
    pub external_customer_id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "plan_code")]
    pub plan_code: String,
    /// Subscription status
    #[serde(rename = "status")]
    pub status: Status,
    /// Billing time
    #[serde(rename = "billing_time")]
    pub billing_time: BillingTime,
    #[serde(rename = "subscription_at")]
    pub subscription_at: String,
    #[serde(rename = "started_at")]
    pub started_at: String,
    #[serde(rename = "terminated_at", skip_serializing_if = "Option::is_none")]
    pub terminated_at: Option<String>,
    #[serde(rename = "canceled_at", skip_serializing_if = "Option::is_none")]
    pub canceled_at: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "previous_plan_code", skip_serializing_if = "Option::is_none")]
    pub previous_plan_code: Option<String>,
    #[serde(rename = "next_plan_code", skip_serializing_if = "Option::is_none")]
    pub next_plan_code: Option<String>,
    #[serde(rename = "downgrade_plan_date", skip_serializing_if = "Option::is_none")]
    pub downgrade_plan_date: Option<String>,
}

impl SubscriptionObject {
    pub fn new(lago_id: uuid::Uuid, external_id: String, lago_customer_id: uuid::Uuid, external_customer_id: String, plan_code: String, status: Status, billing_time: BillingTime, subscription_at: String, started_at: String, created_at: String) -> SubscriptionObject {
        SubscriptionObject {
            lago_id,
            external_id,
            lago_customer_id,
            external_customer_id,
            name: None,
            plan_code,
            status,
            billing_time,
            subscription_at,
            started_at,
            terminated_at: None,
            canceled_at: None,
            created_at,
            previous_plan_code: None,
            next_plan_code: None,
            downgrade_plan_date: None,
        }
    }
}

/// Subscription status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "terminated")]
    Terminated,
    #[serde(rename = "canceled")]
    Canceled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// Billing time
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingTime {
    #[serde(rename = "calendar")]
    Calendar,
    #[serde(rename = "anniversary")]
    Anniversary,
}

impl Default for BillingTime {
    fn default() -> BillingTime {
        Self::Calendar
    }
}

