/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscriptionUpdateInput {
    #[serde(rename = "subscription")]
    pub subscription: Box<crate::models::SubscriptionUpdateInputSubscription>,
}

impl SubscriptionUpdateInput {
    pub fn new(subscription: crate::models::SubscriptionUpdateInputSubscription) -> SubscriptionUpdateInput {
        SubscriptionUpdateInput {
            subscription: Box::new(subscription),
        }
    }
}


