/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.20.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscriptionCreateInputSubscription {
    #[serde(rename = "external_customer_id", skip_serializing_if = "Option::is_none")]
    pub external_customer_id: Option<String>,
    #[serde(rename = "plan_code", skip_serializing_if = "Option::is_none")]
    pub plan_code: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "external_id", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    /// Billing time
    #[serde(rename = "billing_time", skip_serializing_if = "Option::is_none")]
    pub billing_time: Option<BillingTime>,
    #[serde(rename = "subscription_at", skip_serializing_if = "Option::is_none")]
    pub subscription_at: Option<String>,
}

impl SubscriptionCreateInputSubscription {
    pub fn new() -> SubscriptionCreateInputSubscription {
        SubscriptionCreateInputSubscription {
            external_customer_id: None,
            plan_code: None,
            name: None,
            external_id: None,
            billing_time: None,
            subscription_at: None,
        }
    }
}

/// Billing time
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingTime {
    #[serde(rename = "calendar")]
    Calendar,
    #[serde(rename = "anniversary")]
    Anniversary,
}

impl Default for BillingTime {
    fn default() -> BillingTime {
        Self::Calendar
    }
}

