/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Wallet {
    #[serde(rename = "wallet")]
    pub wallet: Box<crate::models::WalletObject>,
}

impl Wallet {
    pub fn new(wallet: crate::models::WalletObject) -> Wallet {
        Wallet {
            wallet: Box::new(wallet),
        }
    }
}


