/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "lago_customer_id")]
    pub lago_customer_id: uuid::Uuid,
    #[serde(rename = "external_customer_id")]
    pub external_customer_id: String,
    /// Status
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "rate_amount")]
    pub rate_amount: f32,
    #[serde(rename = "credits_balance")]
    pub credits_balance: f32,
    #[serde(rename = "balance")]
    pub balance: f32,
    #[serde(rename = "balance_cents")]
    pub balance_cents: i32,
    #[serde(rename = "consumed_credits")]
    pub consumed_credits: f32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "expiration_at", skip_serializing_if = "Option::is_none")]
    pub expiration_at: Option<String>,
    #[serde(rename = "last_balance_sync_at", skip_serializing_if = "Option::is_none")]
    pub last_balance_sync_at: Option<String>,
    #[serde(rename = "last_consumed_credit_at", skip_serializing_if = "Option::is_none")]
    pub last_consumed_credit_at: Option<String>,
    #[serde(rename = "terminated_at", skip_serializing_if = "Option::is_none")]
    pub terminated_at: Option<String>,
}

impl WalletObject {
    pub fn new(lago_id: uuid::Uuid, lago_customer_id: uuid::Uuid, external_customer_id: String, status: Status, currency: String, rate_amount: f32, credits_balance: f32, balance: f32, balance_cents: i32, consumed_credits: f32, created_at: String) -> WalletObject {
        WalletObject {
            lago_id,
            lago_customer_id,
            external_customer_id,
            status,
            currency,
            name: None,
            rate_amount,
            credits_balance,
            balance,
            balance_cents,
            consumed_credits,
            created_at,
            expiration_at: None,
            last_balance_sync_at: None,
            last_consumed_credit_at: None,
            terminated_at: None,
        }
    }
}

/// Status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "terminated")]
    Terminated,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

