/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletInputWallet {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "rate_amount")]
    pub rate_amount: f32,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "paid_credits", skip_serializing_if = "Option::is_none")]
    pub paid_credits: Option<f32>,
    #[serde(rename = "granted_credits", skip_serializing_if = "Option::is_none")]
    pub granted_credits: Option<f32>,
    #[serde(rename = "external_customer_id")]
    pub external_customer_id: String,
    #[serde(rename = "expiration_at", skip_serializing_if = "Option::is_none")]
    pub expiration_at: Option<String>,
}

impl WalletInputWallet {
    pub fn new(rate_amount: f32, currency: String, external_customer_id: String) -> WalletInputWallet {
        WalletInputWallet {
            name: None,
            rate_amount,
            currency,
            paid_credits: None,
            granted_credits: None,
            external_customer_id,
            expiration_at: None,
        }
    }
}


