/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletTransactionsPaginated {
    #[serde(rename = "wallet_transactions")]
    pub wallet_transactions: Vec<crate::models::WalletTransactionObject>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl WalletTransactionsPaginated {
    pub fn new(wallet_transactions: Vec<crate::models::WalletTransactionObject>, meta: crate::models::PaginationMeta) -> WalletTransactionsPaginated {
        WalletTransactionsPaginated {
            wallet_transactions,
            meta: Box::new(meta),
        }
    }
}


