/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletTransactionObject {
    #[serde(rename = "lago_id")]
    pub lago_id: uuid::Uuid,
    #[serde(rename = "lago_wallet_id")]
    pub lago_wallet_id: uuid::Uuid,
    /// Status
    #[serde(rename = "status")]
    pub status: Status,
    /// Transaction type
    #[serde(rename = "transaction_type")]
    pub transaction_type: TransactionType,
    #[serde(rename = "amount")]
    pub amount: f32,
    #[serde(rename = "credit_amount")]
    pub credit_amount: f32,
    #[serde(rename = "settled_at", skip_serializing_if = "Option::is_none")]
    pub settled_at: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl WalletTransactionObject {
    pub fn new(lago_id: uuid::Uuid, lago_wallet_id: uuid::Uuid, status: Status, transaction_type: TransactionType, amount: f32, credit_amount: f32, created_at: String) -> WalletTransactionObject {
        WalletTransactionObject {
            lago_id,
            lago_wallet_id,
            status,
            transaction_type,
            amount,
            credit_amount,
            settled_at: None,
            created_at,
        }
    }
}

/// Status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "settled")]
    Settled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
/// Transaction type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "inbound")]
    Inbound,
    #[serde(rename = "outbound")]
    Outbound,
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::Inbound
    }
}

