/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletTransactionInput {
    #[serde(rename = "wallet_transaction")]
    pub wallet_transaction: Box<crate::models::WalletTransactionInputWalletTransaction>,
}

impl WalletTransactionInput {
    pub fn new(wallet_transaction: crate::models::WalletTransactionInputWalletTransaction) -> WalletTransactionInput {
        WalletTransactionInput {
            wallet_transaction: Box::new(wallet_transaction),
        }
    }
}


