/*
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.32.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WalletsPaginated {
    #[serde(rename = "wallets")]
    pub wallets: Vec<crate::models::WalletObject>,
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
}

impl WalletsPaginated {
    pub fn new(wallets: Vec<crate::models::WalletObject>, meta: crate::models::PaginationMeta) -> WalletsPaginated {
        WalletsPaginated {
            wallets,
            meta: Box::new(meta),
        }
    }
}


